/* 非遗美食消消乐：默认进入闯关、108张成组发牌、图标卡面、通关收藏卡 */
var MATCH_LEVELS=[
{id:'boluoye',title:'第 1 关：桲椤叶饼',emoji:'🥟',foodId:'boluoye',cardName:'山野叶香·桲椤叶饼',rarity:'乡土记忆卡',story:'叶片包裹面香与馅香，是秦皇岛乡土蒸食中极有辨识度的味道。',icons:[['leaf','🍃'],['flour','🌾'],['filling','🥬'],['steam','♨️'],['salt','🧂'],['bowl','🥣'],['fire','🔥'],['hand','🤲'],['water','💧']]},
{id:'lvshi_ice',title:'第 2 关：吕氏老冰糕',emoji:'🍦',foodId:'lvshi_ice',cardName:'老城清凉·吕氏老冰糕',rarity:'夏日记忆卡',story:'老冰糕是山海关街巷里的清凉回忆，适合用年轻化小游戏重新传播。',icons:[['milk','🥛'],['sugar','🍬'],['mix','🥄'],['mold','🧊'],['freeze','❄️'],['pack','🎁'],['fruit','🍓'],['cold','🌬️'],['shop','🏠']]},
{id:'ligao_tang',title:'第 3 关：梨膏糖',emoji:'🍐',foodId:'ligao_tang',cardName:'清润梨香·梨膏糖',rarity:'传统糖点卡',story:'梨汁经过熬制凝成糖点，火候、香气和成型过程都适合做成影像展示。',icons:[['pear','🍐'],['sugar','🍬'],['boil','🔥'],['pot','🍯'],['cool','🧊'],['cut','🔪'],['box','🎁'],['spoon','🥄'],['star','✨']]}
];
MATCH_LEVELS.forEach(function(l){l.icons=l.icons.map(function(i){return{id:i[0],emoji:i[1]};});});
var cardCollectionKey='heritage_food_card_collection';
var matchState={levelIndex:0,level:null,cards:[],slots:[],removedCount:0,score:0,locked:false,shuffleLeft:2,undoLeft:3,combo:0,lastEliminateAt:0};
var _cookFoodSelect=document.getElementById('cookFoodSelect'),_cookingArea=document.getElementById('cookingArea');
startMatchLevel(getCurrentLevelIndex());
function getCurrentLevelIndex(){for(var i=MATCH_LEVELS.length-1;i>0;i--){if(localStorage.getItem('match_level_'+i)==='unlocked')return i;}return 0;}
function renderLevelSelect(){var got=loadCollectedCards();_cookFoodSelect.innerHTML='<div class="game-start-panel"><h2>选择关卡</h2><p>通关获得精美非遗美食卡牌。</p></div>'+MATCH_LEVELS.map(function(l,i){var u=i===0||localStorage.getItem('match_level_'+i)==='unlocked',own=got.indexOf(l.id)!==-1;return '<button class="cook-food-btn level-entry '+(u?'':'locked-level')+'" '+(u?'onclick="startMatchLevel('+i+')"':'')+'><span class="emoji">'+l.emoji+'</span><div class="info"><h4>'+l.title+'</h4><p>'+(u?'点击进入闯关':'通关上一关后解锁')+'</p></div><strong class="card-badge">'+(own?'已收集':'待收集')+'</strong></button>';}).join('');}
function startMatchLevel(i){var l=MATCH_LEVELS[i];matchState={levelIndex:i,level:l,cards:buildStackedCards(l),slots:[],removedCount:0,score:0,locked:false,shuffleLeft:2,undoLeft:3,combo:0,lastEliminateAt:0};_cookFoodSelect.classList.add('hidden');_cookingArea.classList.remove('hidden');renderMatchGame();showComboBanner('开始挑战','ready');}
function buildStackedCards(l){var pos=buildPositions(),cards=[],icons=[];for(var g=0;g<36;g++){icons.push(l.icons[g%l.icons.length]);}icons=shuffle(icons);icons.forEach(function(ic,group){for(var k=0;k<3;k++){var p=pos[group*3+k];cards.push(makeCard(ic,group*3+k,p.layer,p.x,p.y));}});return cards.map(function(c,i){c.z=c.layer*100+i;return c;});}
function buildPositions(){var arr=[],layout=[{layer:0,rows:6,cols:6,x:14,y:18},{layer:1,rows:6,cols:6,x:32,y:34},{layer:2,rows:5,cols:5,x:50,y:54},{layer:3,rows:3,cols:3,x:96,y:82},{layer:4,rows:1,cols:2,x:142,y:130}];layout.forEach(function(g){for(var r=0;r<g.rows;r++)for(var c=0;c<g.cols;c++)arr.push({layer:g.layer,x:g.x+c*46,y:g.y+r*37});});return shuffle(arr.slice(0,108));}
function makeCard(ic,i,layer,x,y){return{id:ic.id,emoji:ic.emoji,uid:ic.id+'_'+i+'_'+Math.random().toString(36).slice(2,7),layer:layer,x:x,y:y,z:0,removed:false,picked:false};}
function shuffle(a){return a.sort(function(){return Math.random()-.5;});}
function renderMatchGame(){var total=matchState.cards.length,p=Math.round(matchState.removedCount/total*100);document.getElementById('cookingTitle').textContent=matchState.level.title;document.getElementById('cookingProgress').textContent='进度 '+p+'% · 得分 '+matchState.score+' · 连消 '+matchState.combo;document.getElementById('levelProgressBar').style.width=p+'%';renderTargets();renderBoard();renderSlots();renderTip();}
function renderTargets(){document.getElementById('matchTargets').innerHTML='<div class="mini-rule">第 '+(matchState.levelIndex+1)+' / '+MATCH_LEVELS.length+' 关</div><div class="mini-rule">洗牌 '+matchState.shuffleLeft+'</div><div class="mini-rule">撤回 '+matchState.undoLeft+'</div><div class="mini-rule">槽位 '+matchState.slots.length+'/7</div>';}
function renderBoard(){var s=matchState.cards.slice().sort(function(a,b){return a.z-b.z;});document.getElementById('matchBoard').innerHTML=s.map(function(c){if(c.removed||c.picked)return'';var b=isBlocked(c);return '<button class="stack-card icon-only '+(b?'blocked':'')+'" style="left:'+c.x+'px;top:'+c.y+'px;z-index:'+c.z+';" onclick="pickCard(\''+c.uid+'\')"><span>'+c.emoji+'</span></button>';}).join('');}
function isBlocked(c){return matchState.cards.some(function(o){return o.uid!==c.uid&&!o.removed&&!o.picked&&o.layer>c.layer&&Math.abs(o.x-c.x)<38&&Math.abs(o.y-c.y)<32;});}
function renderSlots(){var h='';for(var i=0;i<7;i++){var c=matchState.slots[i];h+='<div class="match-slot '+(c?'filled slot-pop':'')+'">'+(c?'<span>'+c.emoji+'</span>':'')+'</div>';}document.getElementById('matchSlots').innerHTML=h;}
function renderTip(m){document.getElementById('completedSteps').innerHTML='<div class="match-tip">'+(m||'灰色卡片被上层压住，不能点击。连续快速消除会触发连消加分。')+'</div>';}
function pickCard(uid){if(matchState.locked)return;var c=matchState.cards.find(function(x){return x.uid===uid;});if(!c||c.removed||c.picked)return;if(isBlocked(c)){shakeBoard();renderTip('这张卡被上层压住了，先消除覆盖它的卡片。');return;}if(matchState.slots.length>=7){loseMatch('槽位已满，挑战失败！');return;}c.picked=true;matchState.slots.push(c);floatText(c.emoji,c.x,c.y);var e=eliminateTriples(c.id);if(!e&&matchState.slots.length>=7){renderMatchGame();loseMatch('槽位已满，挑战失败！');return;}renderMatchGame();if(e)renderTip('三连消除！底层又露出来一些。');if(matchState.removedCount>=matchState.cards.length)winMatch();}
function eliminateTriples(id){var same=matchState.slots.filter(function(c){return c.id===id;});if(same.length<3)return false;var now=Date.now();matchState.combo=now-matchState.lastEliminateAt<2600?matchState.combo+1:1;matchState.lastEliminateAt=now;var rm=0,emoji=same[0].emoji;matchState.slots=matchState.slots.filter(function(c){if(c.id===id&&rm<3){c.removed=true;c.picked=false;rm++;matchState.removedCount++;return false;}return true;});var bonus=100+Math.max(0,matchState.combo-1)*50;matchState.score+=bonus;showComboBanner(matchState.combo>1?'连消 x'+matchState.combo+' +'+bonus:'三消 +'+bonus,'combo');burst(emoji);return true;}
function shuffleBoard(){if(matchState.locked||matchState.shuffleLeft<=0)return;matchState.shuffleLeft--;var active=matchState.cards.filter(function(c){return!c.removed&&!c.picked;}),pos=shuffle(active.map(function(c){return{x:c.x,y:c.y,layer:c.layer,z:c.z};}));active.forEach(function(c,i){c.x=pos[i].x;c.y=pos[i].y;c.layer=pos[i].layer;c.z=pos[i].z;});renderMatchGame();showComboBanner('洗牌完成','ready');}
function undoPick(){if(matchState.locked||matchState.undoLeft<=0||!matchState.slots.length)return;var c=matchState.slots.pop();c.picked=false;matchState.undoLeft--;renderMatchGame();showComboBanner('撤回成功','ready');}
function winMatch(){matchState.locked=true;collectCard(matchState.level.id);if(typeof unlockFood==='function')unlockFood(matchState.level.foodId);if(typeof renderFoodCards==='function')renderFoodCards();var n=matchState.levelIndex+1;if(n<MATCH_LEVELS.length)localStorage.setItem('match_level_'+n,'unlocked');confetti();var html='<div class="premium-reward"><p class="reward-kicker">卡牌已收集</p><div class="premium-card"><div class="card-shine"></div><div class="premium-img">'+matchState.level.emoji+'</div><h2>'+matchState.level.cardName+'</h2><strong>'+matchState.level.rarity+'</strong><p>'+matchState.level.story+'</p><span>后续可替换为你的实拍美食图片</span></div><button class="primary-button" onclick="closeModal();backToMatchSelect()">继续闯关</button><button class="small-button" onclick="openCardCollection()">查看卡牌库</button></div>';if(typeof openModal==='function')openModal(html);document.getElementById('completedSteps').innerHTML='<div class="match-tip">通关成功！非遗美食卡牌已加入收集库。</div>';}
function loseMatch(m){matchState.locked=true;shakeBoard();document.getElementById('completedSteps').innerHTML='<div class="match-finish lose"><div class="finish-emoji">😵</div><h3>挑战失败</h3><p>'+m+'</p><button class="primary-button" onclick="restartMatch()">再试一次</button><button class="small-button" onclick="backToMatchSelect()">返回关卡</button></div>';}
function restartMatch(){if(matchState.level)startMatchLevel(matchState.levelIndex);}function backToMatchSelect(){matchState.level=null;matchState.cards=[];matchState.slots=[];matchState.removedCount=0;matchState.score=0;matchState.locked=false;_cookingArea.classList.add('hidden');_cookFoodSelect.classList.remove('hidden');renderLevelSelect();}
function collectCard(id){var a=loadCollectedCards();if(a.indexOf(id)===-1){a.push(id);localStorage.setItem(cardCollectionKey,JSON.stringify(a));}}
function loadCollectedCards(){try{return JSON.parse(localStorage.getItem(cardCollectionKey))||[];}catch(e){return[];}}
function openCardCollection(){var got=loadCollectedCards(),html='<h3>非遗美食卡牌收集库</h3><p>通关主游戏后可获得对应卡牌。</p><div class="card-library">'+MATCH_LEVELS.map(function(l){var o=got.indexOf(l.id)!==-1;return '<div class="library-card '+(o?'owned':'locked')+'"><div class="card-emoji">'+(o?l.emoji:'❔')+'</div><strong>'+(o?l.cardName:'未解锁卡牌')+'</strong><span>'+(o?l.rarity:'继续闯关获得')+'</span><small>'+(o?l.story:'通关 '+l.title+' 后解锁')+'</small></div>';}).join('')+'</div>';if(typeof openModal==='function')openModal(html);}
function openFeatureWindow(t){var d={documentary:['🎬','纪录片窗口','这里后续放三下乡纪录片、调研短片或非遗美食宣传视频。'],steps:['🧑‍🍳','制作步骤窗口','这里展示桲椤叶饼、吕氏老冰糕、梨膏糖的图文制作步骤。'],interview:['🎙️','传承人采访窗口','这里放店主、师傅、传承人采访语录、照片和音视频片段。']}[t];if(d&&typeof openModal==='function')openModal('<div class="feature-window"><div class="feature-icon">'+d[0]+'</div><h3>'+d[1]+'</h3><p>'+d[2]+'</p><div class="media-slot">素材待接入</div></div>');}
function showComboBanner(t,cls){var b=document.getElementById('comboBanner');if(!b)return;b.textContent=t;b.className='combo-banner '+(cls||'combo');setTimeout(function(){b.classList.add('hidden');},950);}
function floatText(t,x,y){var b=document.getElementById('matchBoard');if(!b)return;var e=document.createElement('div');e.className='floating-score';e.textContent=t;e.style.left=x+'px';e.style.top=y+'px';b.appendChild(e);setTimeout(function(){if(e.parentNode)e.parentNode.removeChild(e);},700);}
function burst(emoji){var b=document.getElementById('matchBoard');if(!b)return;for(var i=0;i<12;i++){var p=document.createElement('div');p.className='burst-particle';p.textContent=i%3===0?emoji:'✨';p.style.left=145+Math.random()*80+'px';p.style.top=120+Math.random()*70+'px';p.style.setProperty('--dx',Math.random()*120-60+'px');p.style.setProperty('--dy',Math.random()*-90-20+'px');b.appendChild(p);setTimeout((function(x){return function(){if(x.parentNode)x.parentNode.removeChild(x);};})(p),850);}}
function confetti(){for(var i=0;i<28;i++){var c=document.createElement('div');c.className='win-confetti';c.textContent=['✨','🎉','⭐','🏮'][i%4];c.style.left=Math.random()*100+'vw';c.style.animationDelay=Math.random()*.4+'s';document.body.appendChild(c);setTimeout((function(x){return function(){if(x.parentNode)x.parentNode.removeChild(x);};})(c),1800);}}
function shakeBoard(){var b=document.getElementById('matchBoard');if(!b)return;b.classList.add('board-shake');setTimeout(function(){b.classList.remove('board-shake');},350);}
